In [1]:
from general_extraction_methods import *

import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

%load_ext autoreload
%autoreload 2

In [2]:
# debugging specific visualizations
def colorize_categories(x):
    if x == 'beg_nav':
        return 'background-color: rgba(255,255,0,.2)'
    elif x == 'contributions':
        return 'background-color: rgba(0,255,255,.2)'
    elif x == 'distributions':
        return 'background-color: rgba(255,0,0,.2)'
    elif x == 'end_nav':
        return 'background-color: rgba(0,255,0,.2)'
    elif x == 'nav':
        return 'background-color: rgba(255,0,255,.2)'
    else: # x == 'unfunded' 
        return 'background-color: rgba(0,0,255,.2)'

In [6]:
current_tester = 'Kartikaye'

sean_validation_df = pd.read_excel('cab_validation_' + current_tester.lower() + '.xlsx')
sean_validation_df = sean_validation_df[sean_validation_df['Assigned'] == current_tester]

file_list = list(set(sean_validation_df['file']))

omni_conxn_str = 'mysql+pymysql://bwong:?(}9LcsW@analytics-proxy.stepstoneapps.com/spar_analytics'
lgclf = gen_model(omni_conxn_str)

input_folder = 'text_extracting_folder_test'
pdf_img_dict = generate_pdf_img_dict(input_folder, file_list = file_list)
file_list = list(pdf_img_dict.keys())
file_list.sort()

pre-cleaning data...
 - dropping null values
 - lowercasing, removing punctuation, removing numbers
 - remove empty strings
logistic classifier testing accuracy 0.9706959706959707

In [7]:
# test case
file = '2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf' #file_list[4]
print('analyzing file: ' + str(file))

cleaned_data_df = generate_text_data(pdf_img_dict[file])
high_confidence_img, best_img, high_confidence_df, best_guess_df, raw_predictions_df = get_predictions(pdf_img_dict[file], cleaned_data_df, lgclf)

high_confidence_df['file'] = [file for x in range(len(high_confidence_df))]
best_guess_df['file'] = [file for x in range(len(best_guess_df))]

high_confidence_df = high_confidence_df.sort_values(['file','predicted_category', 'prediction_confidence'], ascending=[True, True, False])
best_guess_df = best_guess_df.sort_values(['file','predicted_category', 'prediction_confidence'], ascending=[True, True, False])

#raw_predictions_df

analyzing file: 2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf
pre-cleaning data...
 - dropping null values
 - lowercasing, removing punctuation, removing numbers
 - remove empty strings
getting category predictions...
 - categories found: {'unfunded', 'distributions', 'contributions', 'nav'}

In [20]:
# 2021.09.30.CAB.Lone Star RE III.Bermuda.GOSI.pdf: erroneous beg_nav

def test_method(x):
    sorted_df = x.sort_values(['prediction_confidence'], ascending = False)
    if sorted_df.iloc[0]['prediction_confidence'] > .6:
        if sorted_df.iloc[0]['predicted_category'] == 'nav':
            #return sorted_df.head(2)
            return sorted_df[sorted_df['prediction_confidence'] > .6]
        else:
            return sorted_df[sorted_df['prediction_confidence'] > .6]
    else:
        if sorted_df.iloc[0]['predicted_category'] == 'nav':
            return sorted_df.head(2) 
        else:
            return sorted_df.head(1)

potential_answers_df = raw_predictions_df.groupby('predicted_category').apply(lambda x: test_method(x)).reset_index(drop = True).sort_values(['predicted_category', 'prediction_confidence'], ascending = [True, False])
potential_answers_df.style.applymap(colorize_categories, subset=['predicted_category'])

In [6]:
'''
post cleaning rules:
- only accept predictions greater than 40%
- do best guess of navs 
'''

cleaner_answers_df = potential_answers_df[potential_answers_df['prediction_confidence'] > .4]
if len(cleaner_answers_df) != len(potential_answers_df):
    print(' - dropped some predicted values due to low confidence')

'''
nav_rows = cleaner_answers_df[cleaner_answers_df['predicted_category'] == 'nav']
nav_rows['x_coord'] = nav_rows['final_coord_block_par_line_group'].apply(lambda x: x[1])
nav_rows = nav_rows.sort_values(['x_coord'])
nav_rows['predicted_category'] = ['beg_nav', 'end_nav']
cleaner_answers_df[cleaner_answers_df['predicted_category'] == 'nav'] = nav_rows
'''

cleaner_answers_df = cleaner_answers_df.sort_values(['predicted_category', 'prediction_confidence'], ascending = [True, False])
cleaner_answers_df.style.applymap(colorize_categories, subset=['predicted_category'])

# trying to pull numerical data

In [5]:
current_tester = 'Kartikaye'

sean_validation_df = pd.read_excel('cab_validation_' + current_tester.lower() + '.xlsx')
sean_validation_df = sean_validation_df[sean_validation_df['Assigned'] == current_tester]

file_list = list(set(sean_validation_df['file']))

omni_conxn_str = 'mysql+pymysql://bwong:?(}9LcsW@analytics-proxy.stepstoneapps.com/spar_analytics'
lgclf = gen_model(omni_conxn_str)

input_folder = 'text_extracting_folder_test'
pdf_img_dict = generate_pdf_img_dict(input_folder, file_list = file_list)
file_list = list(pdf_img_dict.keys())
file_list.sort()

logistic classifier testing accuracy 0.967032967032967

In [6]:
def category_selection(x):
    sorted_df = x.sort_values(['prediction_confidence'], ascending = False)
    if sorted_df.iloc[0]['prediction_confidence'] > .6:  
        if sorted_df.iloc[0]['predicted_category'] == 'nav':
            #return sorted_df.head(2)
            return sorted_df[sorted_df['prediction_confidence'] > .6]
        else:
            return sorted_df[sorted_df['prediction_confidence'] > .6]
    else:
        if sorted_df.iloc[0]['predicted_category'] == 'nav':
            return sorted_df.head(2) 
        else:
            return sorted_df.head(1)

def compare_y_coord(x):
        if x['quarter_coord'][0] < x['year_coord'][0]:
            return 'left'
        else:
            return 'right'
            
def generalize_quarter_area(cleaned_data_df):
    potential_quarter_data = cleaned_data_df[cleaned_data_df['text'].apply(lambda x: any(y in x.lower() for y in ['period','current','quarter', 'qtd']))]
    potential_year_data = cleaned_data_df[cleaned_data_df['text'].apply(lambda x: any(y in x.lower() for y in ['year', 'ytd', 'itd']))]
    
    potential_groups = set(potential_quarter_data['group_index']) & set(potential_year_data['group_index'])
    potential_quarter_data = potential_quarter_data[potential_quarter_data['group_index'].apply(lambda x: x in potential_groups)].drop_duplicates('combined_block_text')
    potential_year_data = potential_year_data[potential_year_data['group_index'].apply(lambda x: x in potential_groups)].drop_duplicates('combined_block_text')
    #print(' - number of quarter options: ' + str(len(potential_quarter_data)))
    #print(' - number of year options: ' + str(len(potential_year_data)))
    guessed_answer = 'left*'
    
    if len(potential_quarter_data) != 0 and len(potential_year_data) != 0:
        decision_df1 = potential_quarter_data[['group_index','coord_item']].rename({'coord_item':'quarter_coord'}, axis = 1)
        decision_df2 = potential_year_data[['group_index','coord_item']].rename({'coord_item':'year_coord'}, axis = 1)
        merged_decision_df = pd.merge(left = decision_df1, right = decision_df2, on = 'group_index')
        merged_decision_df['decision'] = merged_decision_df.apply(lambda x: compare_y_coord(x), axis = 1)
        #print(' - ' + str(set(merged_decision_df['decision'])))
        if len(set(merged_decision_df['decision'])) == 1:
            guessed_answer = merged_decision_df['decision'][0]
        else:
            guessed_answer = 'left**'

    return guessed_answer


final_df = pd.DataFrame()
cleaner_answers_dict = {}
all_data_dict = {}
'''
file_list = ['2021.09.30.CAB.FTV III.SS Intl IV Guernsey.pdf', '2021.09.30.CAB.FTV Vagaro.HESTA.pdf', '2021.09.30.CAB.Fortress Japan II Yen B.Mesirow Intl.pdf',
            '2021.09.30.CAB.Fortress Japan III Dollar B.CIRS.pdf', '2021.09.30.CAB.HarbourVest IPEP III Partnership.PASERS.pdf', '2021.09.30.CAB.HarbourVest NYSTRS CoInv III.NYSTRS.pdf',
            '2021.09.30.CAB.Insight II.LAFPP.pdf', '2021.09.30.CAB.Lone Star RE III.Bermuda.GOSI.pdf', '2021.09.30.CAB.Madison Inda IV.SSOF II Off.pdf',
            '2021.09.30.CAB.Madison Realty Debt IV.Texas Schools.pdf', '2021.09.30.CAB.Maple H2.NYSTRS.pdf', 
            '2021.09.30.CAB.Maple H3.NYSTRS.pdf','2021.09.30.CAB.New Mountain II.NYCFIRE.pdf', '2021.09.30.CAB.SRE Care.SREP III.pdf']
'''
for file in file_list:
    print(file)
    cleaned_data_df = generate_text_data(pdf_img_dict[file])
    high_confidence_img, best_img, high_confidence_df, best_guess_df, raw_predictions_df = get_predictions(pdf_img_dict[file], cleaned_data_df, lgclf)
    
    high_confidence_df['file'] = [file for x in range(len(high_confidence_df))]
    best_guess_df['file'] = [file for x in range(len(best_guess_df))]
    
    high_confidence_df = high_confidence_df.sort_values(['file','predicted_category', 'prediction_confidence'], ascending=[True, True, False])
    best_guess_df = best_guess_df.sort_values(['file','predicted_category', 'prediction_confidence'], ascending=[True, True, False])

    potential_answers_df = raw_predictions_df.groupby('predicted_category').apply(lambda x: test_method(x)).reset_index(drop = True).sort_values(['predicted_category', 'prediction_confidence'], ascending = [True, False])

    cleaner_answers_df = potential_answers_df[potential_answers_df['prediction_confidence'] > .4]
    if len(cleaner_answers_df) != len(potential_answers_df):
        print(' - dropped some predicted values due to low confidence')
    
    cleaner_answers_df = cleaner_answers_df.sort_values(['predicted_category', 'prediction_confidence'], ascending = [True, False])
    cleaner_answers_dict[file] = cleaner_answers_df
    
    rows_df = cleaned_data_df[cleaned_data_df['group_index'].apply(lambda x: x in set(cleaner_answers_df['group_index']))]
    rows_df['text'] = rows_df['text'].apply(lambda x: '$0' if x == 'SO' else x) # hardcoded rule, might have to add/remove
    rows_df = rows_df[rows_df['text'].apply(lambda x: any(char.isdigit() for char in x) | (x == '-'))] # limits to rows with at least 1 number
    #rows_df = rows_df[rows_df['text'].apply(lambda x: is_date(x, fuzzy = True) == False)] # remove dates
    pulled_values_df = rows_df[['combined_block_text', 'text', 'group_index']]#.groupby('group_index').nth([-1])[['combined_block_text', 'text', 'group_index']] # assuming 1 value
    #pulled_values_df['text'] = pulled_values_df['text'].apply(lambda x: x.replace('S', '$').replace('s', '$').replace('O', '0').replace('o', '0'))

    test_df = pd.merge(
        left = cleaner_answers_df[['preprocessed_text','group_index', 'predicted_category', 'prediction_confidence', 'final_coord_block_par_line_group']],
        right = pulled_values_df,
        on = 'group_index',
        how = 'right'
    )
    test_df = test_df.rename({'text': 'extracted_value'}, axis = 1)
    test_df['file'] = [file for x in range(len(test_df))]
    test_df = test_df.sort_values(['file','predicted_category', 'prediction_confidence'], ascending=[True, True, False])

    # RECATEGORIZING NAVs AFTER NUMBERS HAVE BEEN PULLED; ASSUME FIRST TWO ROWS WITH NUMERIC VALUES ARE THE BEG_NAV/END_NAV
    # TODO: what happens if beg_nav is found and not end_nav or vice versa?
    def nav_categorizer(x, group_set): 
        if x['predicted_category'] != 'nav':
            return True
        else: 
            return x['group_index'] in group_set
    
    top_nav_groups_w_num = set(test_df[test_df['predicted_category'] == 'nav']['group_index'].drop_duplicates()[:2])
    test_df = test_df[test_df.apply(lambda x: nav_categorizer(x, top_nav_groups_w_num), axis =1)] # removing all navs except first two (top 2 confidence)
    
    nav_rows = test_df[test_df['predicted_category'] == 'nav']
    nav_rows['x_coord'] = nav_rows['final_coord_block_par_line_group'].apply(lambda x: x[1])
    nav_rows = nav_rows.sort_values(['x_coord'])
    beg_nav_group_num = nav_rows[['group_index']].drop_duplicates()['group_index'].iloc[0]
    nav_rows['predicted_category'] = nav_rows['group_index'].apply(lambda x: 'beg_nav' if x == beg_nav_group_num else 'end_nav')
    test_df[test_df['predicted_category'] == 'nav'] = nav_rows

    test_df = test_df.drop(['final_coord_block_par_line_group'], axis = 1)
    test_df = test_df.sort_values(['file','predicted_category', 'prediction_confidence'], ascending=[True, True, False])

    test_df = pd.merge(
        left = test_df, 
        right = test_df.groupby('group_index').size().rename('num_cols'), 
        on = 'group_index'
    )
    
    # guessing quarter location (left or right)
    location_guess = generalize_quarter_area(cleaned_data_df)
    print(' - data we want is on the \'' + location_guess + '\' side')
    if 'left' in location_guess:
        narrowed_df = test_df.drop_duplicates('group_index', keep = 'first')
    else:
        narrowed_df = test_df.drop_duplicates('group_index', keep = 'last')

    test_df['guessed_quarter_loc'] = [location_guess for _ in range(len(test_df))]
    all_data_dict[file] = test_df
    
    final_df = pd.concat([final_df, narrowed_df])

2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.AG Net Lease Realty IV.TransGlobe Life Insurance.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left**' side
2021.09.30.CAB.ASF VII B NYC CoInv.NYCERS.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left*' side
2021.09.30.CAB.ASF VIII B NYC CoInv.NYCERS.pdf
 - categories found: {'unfunded', 'nav', 'contributions'}
 - data we want is on the 'left*' side
2021.09.30.CAB.Almanac Realty V.NY Teamsters.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'right' side
2021.09.30.CAB.Almanac Realty VIII SC II.NYCTRS.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'right' side
2021.09.30.CAB.American Industrial VI.Saudi.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left*' side
2021.09.30.CAB.American VI.SS H.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left*' side
2021.09.30.CAB.Ares Europe III.TransGlobe.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Ares Pathfinder.HKJC.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Audax Direct Lending.PASERS.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Audax III.PASERS.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Bain IX CoInv.GESB.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Bain XII.Midland.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Blackstone Infra.ILTRS Supplemental.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Blackstone Prop Euro.CalSTRS.pdf
 - categories found: {'distributions', 'nav', 'contributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Brookfield Premier RE.NYCERS.pdf
 - categories found: {'contributions', 'unfunded', 'nav', 'distributions'}
 - data we want is on the 'left' side
2021.09.30.CAB.Brookfield Timberland V.UN.pdf
 - categories found: {'unfunded', 'nav', 'contributions'}
 - data we want is on the 'left*' side

In [7]:
visualize_df = final_df.reset_index(drop = True)

In [8]:
test_file = '2021.09.30.CAB.American Industrial VI.Saudi.pdf'
visualize_df[visualize_df['file'] == test_file][['preprocessed_text', 'predicted_category', 'extracted_value', 'file']].style.applymap(colorize_categories, subset=['predicted_category'])

In [16]:
#cleaner_answers_dict[test_file].style.applymap(colorize_categories, subset=['predicted_category'])
#all_data_dict[test_file].style.applymap(colorize_categories, subset=['predicted_category'])

In [13]:
'''
potential rules:
- for each group, we want the smallest value (excluding empty values like '-')
- for number checker, check if right value is number, otherwise it's not a valid option. logic is used to counter the - in 'Contributions - Syndication Costs 0 0 0' 
'''

"\npotential rules:\n- for each group, we want the smallest value (excluding empty values like '-')\n- for number checker, check if right value is number, otherwise it's not a valid option. logic is used to counter the - in 'Contributions - Syndication Costs 0 0 0' \n"

In [9]:
final_df

,preprocessed_text,group_index,predicted_category,prediction_confidence,combined_block_text,extracted_value,file,num_cols
0,net asset value beginning of period,19,beg_nav,0.968340,"Net Asset Value, Beginning of Period $ 3,274,9...","3,274,937",2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf,2
2,contributions,21,contributions,0.994592,Contributions - -,-,2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf,2
4,cumulative contributions contributed,9,contributions,0.948300,"Cumulative Contributions ($18,750,000) % Contr...","($18,750,000)",2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf,2
6,net asset value end of period,32,end_nav,0.934597,"Net Asset Value, End of Period $ 3,753,043 $ 3...","3,753,043",2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf,2
8,unfunded capital commitment,13,unfunded,0.985238,"Unfunded Capital Commitment $2,319,783","$2,319,783",2021.09.30.CAB.AG Energy Credit Opps.CCCERA.pdf,1
...,...,...,...,...,...,...,...,...
26,partners capital after incentive allocation,29,end_nav,0.899802,Partner's Capital after Incentive Allocation $...,"226,653,645.15",2021.09.30.CAB.Brookfield Premier RE.NYCERS.pdf,6
32,available commitment net,34,unfunded,0.904257,"Available Commitment $ - Net $ 23,925 253.23",-,2021.09.30.CAB.Brookfield Premier RE.NYCERS.pdf,3
0,as at,2,beg_nav,0.819857,"As at September 30, 2021","30,",2021.09.30.CAB.Brookfield Timberland V.UN.pdf,2
2,partner contributions losses losses expenses fees,8,contributions,0.649247,PARTNER CONTRIBUTIONS (LOSSES) (LOSSES) EXPENS...,"30,",2021.09.30.CAB.Brookfield Timberland V.UN.pdf,2
4,represents uncollected carried interest assumi...,41,end_nav,0.803809,(1) Represents uncollected carried interest as...,(1),2021.09.30.CAB.Brookfield Timberland V.UN.pdf,1

In [ ]:
# work on separating headers from data 
# work on improving extractions